# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

# name: Publish to AliyunOSS

# on:
#   push:
#     branches:
#       - "deploy"

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v2
#         with:
#           node-version: 14
#       - run: yarn install
#       - run: yarn run build
#       - name: Upload AliyunOSS
#         uses: fangbinwei/aliyun-oss-website-action@v1
#         with:
#           accessKeyId: ${{ secrets.ACCESS_KEY_ID }}
#           accessKeySecret: ${{ secrets.ACCESS_KEY_SECRET }}
#           bucket: "yaklang-io"
#           endpoint: "oss-accelerate-overseas.aliyuncs.com"
#           folder: "./build"

# 新Github-Ci
name: Yarn Build CI

on:
    push:
        branches:
            - 'develop'
        # tags:
        #     - 'v*'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@master
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 22.7

            # 打包
            - name: build
              run: pnpm install
            - run: pnpm run build

            # 静态文件压缩
            - name: pack out file
              if: ${{ startsWith(github.ref, 'refs/tags/v') }}
              run: tar -zcvf out.tgz dist
