version: "2.2"

services:
  frontend:
    image: v1ll4n/legion-frontend-aes:latest
    ports:
      - "8992:8080"
    environment:
      # - REVERSE_PROXY_HOST=127.0.0.1
      - REVERSE_PROXY_PORT=8082
      - LISTEN_HTTP_PORT=8080
      # nginx lua的key
      - AES_KEY=0123456789abcdef
      - AES_IV=fedcba9876543210
      # react 的key
      - REACT_APP_AES_KEY=0123456789abcdef
      - REACT_APP_AES_IV=fedcba9876543210
#    network_mode: "host"
