/** @name 图标对应关系(yak-runner文件树) */
export const KeyToIcon: Record<string, { iconPath: string }> = {
    _file: { iconPath: './icons/file.svg' },
    _fd_default: { iconPath: './icons/folders/default.svg' },
    '_fd_default-open': { iconPath: './icons/folders/default-open.svg' },
    _fd_root: { iconPath: './icons/folders/root.svg' },
    '_fd_root-open': { iconPath: './icons/folders/root-open.svg' },
    _fd_node: { iconPath: './icons/folders/node.svg' },
    '_fd_node-open': { iconPath: './icons/folders/node-open.svg' },
    _fd_bower: { iconPath: './icons/folders/bower.svg' },
    '_fd_bower-open': { iconPath: './icons/folders/bower-open.svg' },
    _fd_git: { iconPath: './icons/folders/git.svg' },
    '_fd_git-open': { iconPath: './icons/folders/git-open.svg' },
    _fd_tests: { iconPath: './icons/folders/tests.svg' },
    '_fd_tests-open': { iconPath: './icons/folders/tests-open.svg' },
    _fd_vscode: { iconPath: './icons/folders/vsc.svg' },
    '_fd_vscode-open': { iconPath: './icons/folders/vsc-open.svg' },
    _fd_jest: { iconPath: './icons/folders/jest.svg' },
    '_fd_jest-open': { iconPath: './icons/folders/jest-open.svg' },
    _fd_build: { iconPath: './icons/folders/build.svg' },
    '_fd_build-open': { iconPath: './icons/folders/build-open.svg' },
    _fd_bench: { iconPath: './icons/folders/bench.svg' },
    '_fd_bench-open': { iconPath: './icons/folders/bench-open.svg' },
    _fd_i18n: { iconPath: './icons/folders/i18n.svg' },
    '_fd_i18n-open': { iconPath: './icons/folders/i18n-open.svg' },
    _fd_views: { iconPath: './icons/folders/views.svg' },
    '_fd_views-open': { iconPath: './icons/folders/views-open.svg' },
    _fd_theme: { iconPath: './icons/folders/theme.svg' },
    '_fd_theme-open': { iconPath: './icons/folders/theme-open.svg' },
    _fd_db: { iconPath: './icons/folders/db.svg' },
    '_fd_db-open': { iconPath: './icons/folders/db-open.svg' },
    _fd_images: { iconPath: './icons/folders/images.svg' },
    '_fd_images-open': { iconPath: './icons/folders/images-open.svg' },
    _fd_save: { iconPath: './icons/folders/save.svg' },
    '_fd_save-open': { iconPath: './icons/folders/save-open.svg' },
    _fd_next: { iconPath: './icons/folders/next.svg' },
    '_fd_next-open': { iconPath: './icons/folders/next-open.svg' },
    _fd_app: { iconPath: './icons/folders/app.svg' },
    '_fd_app-open': { iconPath: './icons/folders/app-open.svg' },
    _fd_cypress: { iconPath: './icons/folders/cypress.svg' },
    '_fd_cypress-open': { iconPath: './icons/folders/cypress-open.svg' },
    _f_jest: { iconPath: './icons/jest.svg' },
    _f_actionscript: { iconPath: './icons/actionscript.png' },
    _f_android: { iconPath: './icons/android.svg' },
    _f_angular: { iconPath: './icons/angular.svg' },
    _f_apache: { iconPath: './icons/apache.svg' },
    _f_applescript: { iconPath: './icons/applescript.svg' },
    _f_autoit: { iconPath: './icons/autoit.svg' },
    _f_binary: { iconPath: './icons/binary.png' },
    _f_blade: { iconPath: './icons/blade.svg' },
    _f_bower: { iconPath: './icons/bower.svg' },
    _f_brunch: { iconPath: './icons/brunch.svg' },
    _f_c: { iconPath: './icons/c.png' },
    '_f_c-h': { iconPath: './icons/c-h.png' },
    _f_cake: { iconPath: './icons/cake.png' },
    _f_codekit: { iconPath: './icons/codekit.svg' },
    _f_coffeescript: { iconPath: './icons/coffeescript.svg' },
    _f_coldfusion: { iconPath: './icons/coldfusion.png' },
    _f_cfm: { iconPath: './icons/cfm.png' },
    _f_cfc: { iconPath: './icons/cfc.png' },
    _f_clojure: { iconPath: './icons/clojure.svg' },
    _f_cakephp: { iconPath: './icons/cakephp.svg' },
    _f_cmake: { iconPath: './icons/cmake.svg' },
    _f_cpp: { iconPath: './icons/cpp.svg' },
    '_f_cpp-h': { iconPath: './icons/cpp-h.png' },
    _f_crystal: { iconPath: './icons/crystal.svg' },
    _f_csharp: { iconPath: './icons/csharp.svg' },
    _f_css: { iconPath: './icons/css.svg' },
    _f_database: { iconPath: './icons/database.svg' },
    _f_database2: { iconPath: './icons/database2.svg' },
    _f_docker: { iconPath: './icons/docker.svg' },
    _f_dotenv: { iconPath: './icons/dotenv.svg' },
    _f_dust: { iconPath: './icons/dust.png' },
    _f_ejs: { iconPath: './icons/ejs.svg' },
    _f_elixir: { iconPath: './icons/elixir.svg' },
    _f_elm: { iconPath: './icons/elm.svg' },
    _f_erlang: { iconPath: './icons/erlang.png' },
    _f_eslint: { iconPath: './icons/eslint.svg' },
    _f_exe: { iconPath: './icons/exe.png' },
    _f_font: { iconPath: './icons/font.svg' },
    _f_fsharp: { iconPath: './icons/fsharp.svg' },
    _f_gherkin: { iconPath: './icons/gherkin.png' },
    _f_git: { iconPath: './icons/git.svg' },
    _f_go: { iconPath: './icons/go.svg' },
    _f_gnu: { iconPath: './icons/gnu.svg' },
    _f_gradle: { iconPath: './icons/gradle.svg' },
    _f_graphviz: { iconPath: './icons/graphviz.png' },
    _f_grunt: { iconPath: './icons/grunt.svg' },
    _f_gulp: { iconPath: './icons/gulp.svg' },
    _f_haml: { iconPath: './icons/haml.png' },
    _f_handlebars: { iconPath: './icons/handlebars.svg' },
    _f_haskell: { iconPath: './icons/haskell.svg' },
    _f_haxe: { iconPath: './icons/haxe.svg' },
    _f_html: { iconPath: './icons/html.svg' },
    _f_illustrator: { iconPath: './icons/illustrator.svg' },
    _f_image: { iconPath: './icons/image.png' },
    _f_icon: { iconPath: './icons/icon.png' },
    _f_jade: { iconPath: './icons/jade.svg' },
    _f_java: { iconPath: './icons/java.svg' },
    '_f_java-alt': { iconPath: './icons/java-alt.svg' },
    _f_javascript: { iconPath: './icons/javascript.svg' },
    _f_jenkinsfile: { iconPath: './icons/jenkins.svg' },
    _f_json: { iconPath: './icons/json.svg' },
    _f_julia: { iconPath: './icons/julia.svg' },
    _f_karma: { iconPath: './icons/karma.svg' },
    _f_key: { iconPath: './icons/key.png' },
    _f_less: { iconPath: './icons/less.svg' },
    _f_liquid: { iconPath: './icons/liquid.svg' },
    _f_markdown: { iconPath: './icons/markdown.svg' },
    _f_matlab: { iconPath: './icons/matlab.svg' },
    '_f_matlab-alt': { iconPath: './icons/matlab-red.svg' },
    _f_mdx: { iconPath: './icons/mdx.svg' },
    _f_mjml: { iconPath: './icons/mjml.svg' },
    _f_mocha: { iconPath: './icons/mocha.svg' },
    _f_mustache: { iconPath: './icons/mustache.png' },
    _f_nginx: { iconPath: './icons/nginx.svg' },
    _f_nim: { iconPath: './icons/nim.svg' },
    _f_node: { iconPath: './icons/node.svg' },
    _f_npm: { iconPath: './icons/npm.svg' },
    _f_nsis: { iconPath: './icons/nsis.svg' },
    _f_nuget: { iconPath: './icons/nuget.svg' },
    _f_nunjucks: { iconPath: './icons/nunjucks.svg' },
    _f_ocaml: { iconPath: './icons/ocaml.svg' },
    _f_paket: { iconPath: './icons/paket.png' },
    _f_pdf: { iconPath: './icons/pdf.svg' },
    _f_perl: { iconPath: './icons/perl.png' },
    _f_phalcon: { iconPath: './icons/phalcon.svg' },
    _f_photoshop: { iconPath: './icons/photoshop.svg' },
    _f_php: { iconPath: './icons/php.svg' },
    _f_postcss: { iconPath: './icons/postcss.svg' },
    _f_powershell: { iconPath: './icons/powershell.png' },
    _f_pug: { iconPath: './icons/pug.png' },
    _f_python: { iconPath: './icons/python.svg' },
    _f_razor: { iconPath: './icons/razor.png' },
    _f_react: { iconPath: './icons/react.svg' },
    _f_react_alt: { iconPath: './icons/react-alt.svg' },
    _f_rlang: { iconPath: './icons/rlang.png' },
    _f_ruby: { iconPath: './icons/ruby.svg' },
    _f_rust: { iconPath: './icons/rust.svg' },
    _f_sass: { iconPath: './icons/sass.svg' },
    _f_scala: { iconPath: './icons/scala.svg' },
    _f_settings: { iconPath: './icons/settings.svg' },
    '_f_settings-red': { iconPath: './icons/settings-red.svg' },
    _f_shell: { iconPath: './icons/shell.png' },
    _f_slim: { iconPath: './icons/slim.svg' },
    _f_source: { iconPath: './icons/source.svg' },
    _f_stylus: { iconPath: './icons/stylus.svg' },
    _f_sublime: { iconPath: './icons/sublime.svg' },
    _f_svg: { iconPath: './icons/svg.svg' },
    _f_swift: { iconPath: './icons/swift.svg' },
    _f_tcl: { iconPath: './icons/tcl.png' },
    _f_tests: { iconPath: './icons/test.svg' },
    _f_testsjs: { iconPath: './icons/testjs.svg' },
    _f_tex: { iconPath: './icons/tex.svg' },
    _f_textile: { iconPath: './icons/textile.png' },
    _f_todo: { iconPath: './icons/todo.svg' },
    _f_twig: { iconPath: './icons/twig.png' },
    _f_typescript: { iconPath: './icons/typescript.svg' },
    _f_url: { iconPath: './icons/url.png' },
    _f_valgrind: { iconPath: './icons/valgrind.svg' },
    _f_visualstudio: { iconPath: './icons/visualstudio.svg' },
    _f_visualstudiocode: { iconPath: './icons/visualstudiocode.svg' },
    _f_vue: { iconPath: './icons/vue.svg' },
    _f_vitejs: { iconPath: './icons/vitejs.svg' },
    _f_snowpackjs: { iconPath: './icons/snowpackjs.svg' },
    _f_webpack: { iconPath: './icons/webpack.svg' },
    _f_yaml: { iconPath: './icons/yml.svg' },
    _f_yarn: { iconPath: './icons/yarn.svg' },
    _f_zephir: { iconPath: './icons/zephir.svg' },
    _f_zip: { iconPath: './icons/zip.svg' },
    _f_audio: { iconPath: './icons/audio.png' },
    _f_video: { iconPath: './icons/video.png' },
    _f_word: { iconPath: './icons/word.svg' },
    _f_excel: { iconPath: './icons/excel.svg' },
    _f_powerpoint: { iconPath: './icons/powerpoint.svg' },
    _f_favicon: { iconPath: './icons/favicon.svg' },
    _f_xaml: { iconPath: './icons/xaml.png' },
    _f_unity: { iconPath: './icons/unity.svg' },
    _f_contributing: { iconPath: './icons/contributing.png' },
    _f_smarty: { iconPath: './icons/smarty.png' },
    _f_certificate: { iconPath: './icons/certificate.png' },
    _f_babel: { iconPath: './icons/babel.svg' },
    _f_gitlab: { iconPath: './icons/gitlab.svg' },
    _f_arduino: { iconPath: './icons/arduino.svg' },
    _f_opengl: { iconPath: './icons/opengl.svg' },
    _f_dart: { iconPath: './icons/dart.svg' },
    _f_puppet: { iconPath: './icons/puppet.svg' },
    _f_rstudio: { iconPath: './icons/rstudio.svg' },
    _f_solidity: { iconPath: './icons/solidity.svg' },
    _f_lua: { iconPath: './icons/lua.svg' },
    _f_server: { iconPath: './icons/server.png' },
    _f_rollup: { iconPath: './icons/rollup.svg' },
    _f_editorconfig: { iconPath: './icons/editorconfig.png' },
    _f_json5: { iconPath: './icons/json5.svg' },
    _f_graphql: { iconPath: './icons/graphql.svg' },
    _f_graphqls: { iconPath: './icons/graphqls.svg' },
    _f_prettier: { iconPath: './icons/prettier.svg' },
    _f_cuda: { iconPath: './icons/cuda.svg' },
    _f_foxpro: { iconPath: './icons/foxpro.png' },
    _f_kotlin: { iconPath: './icons/kotlin.svg' },
    _f_pascal: { iconPath: './icons/pascal.png' },
    _f_pascalproject: { iconPath: './icons/pascal-project.svg' },
    _f_harbour: { iconPath: './icons/harbour.svg' },
    _f_terraform: { iconPath: './icons/terraform.svg' },
    _f_visualbasic: { iconPath: './icons/visualbasic.svg' },
    _f_rst: { iconPath: './icons/rst.png' },
    _f_tslint: { iconPath: './icons/tslint.svg' },
    _f_reason: { iconPath: './icons/reason.svg' },
    _f_rescript: { iconPath: './icons/rescript.svg' },
    _f_bucklescript: { iconPath: './icons/buckle.png' },
    _f_jupyter: { iconPath: './icons/jupyter.svg' },
    _f_axure: { iconPath: './icons/axure.png' },
    _f_d: { iconPath: './icons/d.png' },
    _f_livescript: { iconPath: './icons/livescript.svg' },
    _f_stylelint: { iconPath: './icons/stylelint.png' },
    _f_docz: { iconPath: './icons/docz.png' },
    _f_prisma: { iconPath: './icons/prisma.svg' },
    _f_toml: { iconPath: './icons/toml.png' },
    _f_storybook: { iconPath: './icons/storybook.svg' },
    _f_verilog: { iconPath: './icons/verilog.png' },
    _f_verilog_sys: { iconPath: './icons/verilog.png' },
    _f_moleculer: { iconPath: './icons/moleculer.svg' },
    _f_svelte: { iconPath: './icons/svelte.svg' },
    _f_mwb: { iconPath: './icons/mysql-workbench.svg' },
    _f_sketch: { iconPath: './icons/sketch.svg' },
    _f_figma: { iconPath: './icons/figma.svg' },
    _f_sequelize: { iconPath: './icons/sequelize.svg' },
    _f_dhall: { iconPath: './icons/dhall.svg' },
    _f_nix: { iconPath: './icons/nix.svg' },
    _f_purescript: { iconPath: './icons/purescript.svg' },
    _f_scheme: { iconPath: './icons/scheme.svg' },
    _f_racket: { iconPath: './icons/racket.svg' },
    _f_jinja: { iconPath: './icons/jinja.svg' },
    _f_abelljs: { iconPath: './icons/abell.svg' },
    _f_webassembly: { iconPath: './icons/wasm.svg' },
    _f_log: { iconPath: './icons/log.svg' },
    _f_notepad: { iconPath: './icons/notepad.svg' },
    _f_browserlist: { iconPath: './icons/browserlist.svg' },
    _f_symfony: { iconPath: './icons/symfony.svg' },
    _f_nextflow: { iconPath: './icons/nextflow.png' },
    _f_singularity: { iconPath: './icons/singularity.svg' },
    _f_fortran: { iconPath: './icons/fortran.svg' },
    _f_oso: { iconPath: './icons/oso.png' },
    _f_asciidoc: { iconPath: './icons/asciidoc.svg' },
    _f_asp: { iconPath: './icons/dotnet.svg' },
    _f_vim: { iconPath: './icons/vim.svg' },
    _f_keystone: { iconPath: './icons/keystone.svg' },
    _f_vitest: { iconPath: './icons/vitest.svg' },
    _f_turborepo: { iconPath: './icons/turborepo.svg' },
    _f_proto: { iconPath: './icons/proto.svg' },
    _f_godot: { iconPath: './icons/godot.svg' },
    _f_tailwind: { iconPath: './icons/tailwind.svg' },
    _f_pnpm: { iconPath: './icons/pnpm.svg' },
    _f_assembly: { iconPath: './icons/assembly.svg' },
    _f_sentry: { iconPath: './icons/sentry.svg' },
    _f_bicep: { iconPath: './icons/bicep.png' },
    _f_vercel: { iconPath: './icons/vercel.svg' },
    _f_nextjs: { iconPath: './icons/nextjs.svg' },
    _f_firebase: { iconPath: './icons/firebase.svg' },
    _f_avalonia: { iconPath: './icons/avalonia.svg' },
    _f_marko: { iconPath: './icons/marko.svg' },
    _f_model: { iconPath: './icons/model.svg' },
    _f_serverless: { iconPath: './icons/serverless.png' },
    _f_xi: { iconPath: './icons/xi.svg' },
    _f_zig: { iconPath: './icons/zig.svg' },
    _f_brainfuck: { iconPath: './icons/brainfuck.svg' },
    _f_cython: { iconPath: './icons/cython.svg' },
    _f_cypress: { iconPath: './icons/cypress.svg' },
    _f_objectivec: { iconPath: './icons/objectivec.svg' },
    _f_objectivecpp: { iconPath: './icons/objectivecpp.svg' },
    _f_flowtyped: { iconPath: './icons/flow.svg' },
    _f_vr: { iconPath: './icons/vr.svg' },
    _f_prql: { iconPath: './icons/database2.svg' },
    _f_prolog: { iconPath: './icons/swi-prolog.svg' },
    _f_groovy: { iconPath: './icons/groovy.svg' },
    _f_yak: { iconPath: './icons/yak.svg' },
    _f_function: { iconPath: './icons/function.svg' },
    _f_title_info: { iconPath: './icons/title-info.svg' },
    _f_title_low: { iconPath: './icons/title-low.svg' },
    _f_title_middle: { iconPath: './icons/title-middle.svg' },
    _f_title_high: { iconPath: './icons/title-high.svg' },
    _f_title_fatal: { iconPath: './icons/title-fatal.svg' },
};

/** 默认文件图标 */
export const FileDefault = '_file';
/** 默认文件夹图标 */
export const FolderDefault = '_fd_default';
/** 默认文件夹打开图标 */
export const FolderDefaultExpanded = '_fd_default-open';

/** @name 文件后缀对应图标 */
export const FileSuffix: Record<string, string> = {
    ai: '_f_illustrator',
    as: '_f_actionscript',
    au3: '_f_autoit',
    htaccess: '_f_apache',
    htaccess_local: '_f_apache',
    htaccess_notlive: '_f_apache',
    htpasswd: '_f_apache',
    bin: '_f_binary',
    o: '_f_binary',
    lib: '_f_binary',
    dll: '_f_binary',
    obj: '_f_binary',
    a: '_f_binary',
    so: '_f_binary',
    pyc: '_f_binary',
    exe: '_f_exe',
    bowerrc: '_f_bower',
    c: '_f_c',
    h: '_f_c-h',
    cake: '_f_cake',
    kit: '_f_codekit',
    coffee: '_f_coffeescript',
    cfc: '_f_cfm',
    cfm: '_f_cfm',
    cfml: '_f_cfm',
    clj: '_f_clojure',
    cljs: '_f_clojure',
    cljc: '_f_clojure',
    edn: '_f_clojure',
    ctp: '_f_cakephp',
    lucee: '_f_coldfusion',
    cmake: '_f_cmake',
    'cmakelists.txt': '_f_cmake',
    cc: '_f_cpp',
    cpp: '_f_cpp',
    hpp: '_f_cpp-h',
    hh: '_f_cpp-h',
    cxx: '_f_cpp',
    cr: '_f_crystal',
    cs: '_f_csharp',
    cshtml: '_f_razor',
    csproj: '_f_visualstudio',
    css: '_f_css',
    dockerignore: '_f_docker',
    dockerfile: '_f_docker',
    'dockerfile.environment': '_f_docker',
    'environment.dockerfile': '_f_docker',
    'docker-compose.dev.yml': '_f_docker',
    'docker-compose-dev.yml': '_f_docker',
    'docker-compose.prod.yml': '_f_docker',
    'docker-compose-prod.yml': '_f_docker',
    'docker-compose.dist.yml': '_f_docker',
    'docker-compose-dist.yml': '_f_docker',
    'dockerfile.dev': '_f_docker',
    'dockerfile.prod': '_f_docker',
    'dockerfile.dist': '_f_docker',
    dust: '_f_dust',
    ejs: '_f_ejs',
    eslintignore: '_f_eslint',
    ex: '_f_elixir',
    exs: '_f_elixir',
    eex: '_f_elixir',
    leex: '_f_elixir',
    heex: '_f_elixir',
    elm: '_f_elm',
    erl: '_f_erlang',
    hrl: '_f_erlang',
    emakefile: '_f_erlang',
    emakerfile: '_f_erlang',
    woff: '_f_font',
    woff2: '_f_font',
    ttf: '_f_font',
    otf: '_f_font',
    eot: '_f_font',
    pfa: '_f_font',
    pfb: '_f_font',
    feature: '_f_gherkin',
    fs: '_f_fsharp',
    fsproj: '_f_visualstudio',
    fsx: '_f_fsharp',
    fsi: '_f_fsharp',
    gitattributes: '_f_git',
    gitmodules: '_f_git',
    go: '_f_go',
    gradle: '_f_gradle',
    haml: '_f_haml',
    has: '_f_haskell',
    hs: '_f_haskell',
    lhs: '_f_haskell',
    lit: '_f_haskell',
    gf: '_f_haskell',
    hbs: '_f_handlebars',
    'hbs.html': '_f_handlebars',
    hx: '_f_haxe',
    hxml: '_f_haxe',
    htm: '_f_html',
    html: '_f_html',
    jpeg: '_f_image',
    jpg: '_f_image',
    gif: '_f_image',
    png: '_f_image',
    bmp: '_f_image',
    ico: '_f_icon',
    webp: '_f_image',
    jade: '_f_jade',
    pug: '_f_pug',
    java: '_f_java',
    class: '_f_java-alt',
    jar: '_f_java',
    js: '_f_javascript',
    es6: '_f_javascript',
    json: '_f_json',
    jl: '_f_julia',
    key: '_f_key',
    pub: '_f_key',
    pem: '_f_key',
    asc: '_f_key',
    ppk: '_f_key',
    less: '_f_less',
    liquid: '_f_liquid',
    md: '_f_markdown',
    markdown: '_f_markdown',
    mdx: '_f_mdx',
    mjml: '_f_mjml',
    fig: '_f_figma',
    mat: '_f_matlab',
    mex: '_f_matlab',
    mexn: '_f_matlab',
    mexrs6: '_f_matlab',
    mn: '_f_matlab',
    mum: '_f_matlab',
    mx: '_f_matlab',
    mx3: '_f_matlab',
    rwd: '_f_matlab',
    slx: '_f_matlab',
    slddc: '_f_matlab',
    smv: '_f_matlab',
    tikz: '_f_matlab',
    xvc: '_f_matlab',
    mst: '_f_mustache',
    nconf: '_f_nginx',
    webmanifest: '_f_node',
    nuspec: '_f_nuget',
    nupkg: '_f_nuget',
    nim: '_f_nim',
    nunjucks: '_f_nunjucks',
    nunjs: '_f_nunjucks',
    nj: '_f_nunjucks',
    njhtml: '_f_nunjucks',
    njk: '_f_nunjucks',
    npmignore: '_f_npm',
    ml: '_f_ocaml',
    mll: '_f_ocaml',
    mli: '_f_ocaml',
    mly: '_f_ocaml',
    ocamlmakefile: '_f_ocaml',
    merlin: '_f_ocaml',
    pdf: '_f_pdf',
    postcss: '_f_postcss',
    postcssrc: '_f_postcss',
    pcss: '_f_postcss',
    perl: '_f_perl',
    pl: '_f_perl',
    pm: '_f_perl',
    php: '_f_php',
    php1: '_f_php',
    php2: '_f_php',
    php3: '_f_php',
    php4: '_f_php',
    php5: '_f_php',
    php6: '_f_php',
    phps: '_f_php',
    phpsa: '_f_php',
    phpt: '_f_php',
    phtml: '_f_php',
    phar: '_f_php',
    ps1: '_f_powershell',
    psc1: '_f_powershell',
    psm1: '_f_powershell',
    ps1xml: '_f_powershell',
    psd1: '_f_powershell',
    pssc: '_f_powershell',
    psd: '_f_photoshop',
    py: '_f_python',
    pyw: '_f_python',
    jsx: '_f_react',
    tsx: '_f_react_alt',
    r: '_f_rlang',
    R: '_f_rlang',
    RData: '_f_rlang',
    rda: '_f_rlang',
    rds: '_f_rlang',
    rprofile: '_f_rlang',
    Rprofile: '_f_rlang',
    rb: '_f_ruby',
    rbs: '_f_ruby',
    erb: '_f_ruby',
    gemfile: '_f_ruby',
    gemspec: '_f_ruby',
    rs: '_f_rust',
    scala: '_f_scala',
    sass: '_f_sass',
    'service.js': '_f_moleculer',
    'service.ts': '_f_moleculer',
    scss: '_f_sass',
    sss: '_f_postcss',
    sln: '_f_visualstudio',
    suo: '_f_visualstudio',
    supp: '_f_valgrind',
    slim: '_f_slim',
    slm: '_f_slim',
    env: '_f_dotenv',
    'env.example': '_f_dotenv',
    'env.development': '_f_dotenv',
    'env.production': '_f_dotenv',
    'env.production.example': '_f_dotenv',
    'env.development.local': '_f_dotenv',
    'env.production.local': '_f_dotenv',
    'env.local': '_f_dotenv',
    'env.local.example': '_f_dotenv',
    'env.test': '_f_dotenv',
    'env.accept': '_f_dotenv',
    'env.acceptance': '_f_dotenv',
    'env.staging': '_f_dotenv',
    'env.staging.example': '_f_dotenv',
    'env.dev': '_f_dotenv',
    ini: '_f_settings',
    conf: '_f_settings',
    properties: '_f_settings',
    load: '_f_settings',
    opt: '_f_settings',
    cnf: '_f_settings',
    makefile: '_f_settings-red',
    rake: '_f_ruby',
    rakefile: '_f_ruby',
    mk: '_f_settings-red',
    config: '_f_settings',
    bat: '_f_shell',
    sh: '_f_shell',
    cmd: '_f_shell',
    bash: '_f_shell',
    zsh: '_f_shell',
    fish: '_f_shell',
    'sublime-project': '_f_sublime',
    'sublime-workspace': '_f_sublime',
    sqlite: '_f_database2',
    sqlite2: '_f_database2',
    sqlite3: '_f_database2',
    sql: '_f_database',
    myd: '_f_database',
    myi: '_f_database',
    ibd: '_f_database',
    trn: '_f_database',
    mysql_hystory: '_f_database',
    db: '_f_database2',
    db2: '_f_database2',
    db3: '_f_database2',
    styl: '_f_stylus',
    stylus: '_f_stylus',
    svg: '_f_svg',
    swift: '_f_swift',
    'test.js': '_f_tests',
    'test.jsx': '_f_tests',
    'test.mjs': '_f_tests',
    'test.ts': '_f_tests',
    'tests.ts': '_f_tests',
    'test.tsx': '_f_tests',
    'tests.tsx': '_f_tests',
    'spec.js': '_f_tests',
    'spec.ts': '_f_tests',
    'spec.tsx': '_f_tests',
    'unit.js': '_f_tests',
    'unit.ts': '_f_tests',
    'unit.tsx': '_f_tests',
    tcl: '_f_tcl',
    texi: '_f_tex',
    tex: '_f_tex',
    bib: '_f_tex',
    textile: '_f_textile',
    todo: '_f_todo',
    twig: '_f_twig',
    ts: '_f_typescript',
    vue: '_f_vue',
    xml: '_f_source',
    axml: '_f_source',
    xaml: '_f_source',
    pex: '_f_source',
    yml: '_f_yaml',
    yaml: '_f_yaml',
    yarnclean: '_f_yarn',
    zip: '_f_zip',
    rar: '_f_zip',
    '7z': '_f_zip',
    tar: '_f_zip',
    gz: '_f_zip',
    bzip2: '_f_zip',
    xz: '_f_zip',
    bz2: '_f_zip',
    'blade.php': '_f_blade',
    nsi: '_f_nsis',
    nsh: '_f_nsis',
    volt: '_f_phalcon',
    zep: '_f_zephir',
    mp3: '_f_audio',
    wav: '_f_audio',
    flac: '_f_audio',
    m4a: '_f_audio',
    aiff: '_f_audio',
    wma: '_f_audio',
    mov: '_f_video',
    webm: '_f_video',
    mp4: '_f_video',
    mpg: '_f_video',
    mpeg: '_f_video',
    mkv: '_f_video',
    flv: '_f_video',
    vob: '_f_video',
    ogv: '_f_video',
    ogg: '_f_video',
    avi: '_f_video',
    m4v: '_f_video',
    qt: '_f_video',
    mp2: '_f_video',
    ppt: '_f_powerpoint',
    pptx: '_f_powerpoint',
    pptm: '_f_powerpoint',
    pot: '_f_powerpoint',
    potm: '_f_powerpoint',
    potx: '_f_powerpoint',
    pps: '_f_powerpoint',
    ppsm: '_f_powerpoint',
    ppsx: '_f_powerpoint',
    ppa: '_f_powerpoint',
    ppam: '_f_powerpoint',
    doc: '_f_word',
    docm: '_f_word',
    docx: '_f_word',
    dot: '_f_word',
    dotm: '_f_word',
    dotx: '_f_word',
    rtf: '_f_word',
    xla: '_f_excel',
    xlam: '_f_excel',
    xls: '_f_excel',
    xlsb: '_f_excel',
    xlsm: '_f_excel',
    xlsx: '_f_excel',
    xlt: '_f_excel',
    xltm: '_f_excel',
    xltx: '_f_excel',
    csv: '_f_excel',
    tsv: '_f_excel',
    cer: '_f_certificate',
    babelrc: '_f_babel',
    'gitlab-ci.yaml': '_f_gitlab',
    'gitlab-ci.yml': '_f_gitlab',
    ino: '_f_arduino',
    glsl: '_f_opengl',
    geom: '_f_opengl',
    comp: '_f_opengl',
    tesc: '_f_opengl',
    tese: '_f_opengl',
    vs: '_f_opengl',
    frag: '_f_opengl',
    vert: '_f_opengl',
    rchit: '_f_opengl',
    task: '_f_opengl',
    dart: '_f_dart',
    pp: '_f_puppet',
    rproj: '_f_rstudio',
    sol: '_f_solidity',
    lua: '_f_lua',
    http: '_f_server',
    json5: '_f_json5',
    gql: '_f_graphql',
    graphql: '_f_graphql',
    gqls: '_f_graphqls',
    graphqls: '_f_graphqls',
    m: '_f_matlab-alt',
    cu: '_f_cuda',
    kt: '_f_kotlin',
    kts: '_f_kotlin',
    fxp: '_f_foxpro',
    pas: '_f_pascal',
    dpr: '_f_pascalproject',
    lpr: '_f_pascalproject',
    hbp: '_f_harbour',
    hbc: '_f_harbour',
    prg: '_f_exe',
    tf: '_f_terraform',
    tfvars: '_f_terraform',
    vb: '_f_visualbasic',
    cls: '_f_visualbasic',
    frm: '_f_visualbasic',
    bas: '_f_visualbasic',
    doccls: '_f_visualbasic',
    rst: '_f_rst',
    re: '_f_reason',
    rei: '_f_reason',
    res: '_f_rescript',
    resi: '_f_rescript',
    ipynb: '_f_jupyter',
    rp: '_f_axure',
    d: '_f_d',
    di: '_f_d',
    msbuild: '_f_visualstudiocode',
    props: '_f_settings',
    targets: '_f_settings',
    proj: '_f_visualstudio',
    jsproj: '_f_visualstudio',
    sqlproj: '_f_visualstudio',
    vbproj: '_f_visualstudio',
    vcxproj: '_f_visualstudio',
    wixproj: '_f_visualstudio',
    dbproj: '_f_visualstudio',
    lsproj: '_f_visualstudio',
    modelproj: '_f_visualstudio',
    vcproj: '_f_visualstudio',
    wwaproj: '_f_visualstudio',
    ls: '_f_livescript',
    stylelintrc: '_f_stylelint',
    stylelintignore: '_f_stylelint',
    htmlhintrc: '_f_settings',
    prisma: '_f_prisma',
    toml: '_f_toml',
    'story.js': '_f_storybook',
    'story.jsx': '_f_storybook',
    'story.ts': '_f_storybook',
    'story.tsx': '_f_storybook',
    'stories.js': '_f_storybook',
    'stories.jsx': '_f_storybook',
    'stories.ts': '_f_storybook',
    'stories.tsx': '_f_storybook',
    storybook: '_f_storybook',
    v: '_f_verilog',
    vh: '_f_verilog',
    vo: '_f_verilog',
    sv: '_f_verilog_sys',
    vhd: '_f_verilog',
    vhdl: '_f_verilog',
    svelte: '_f_svelte',
    'svelte.js': '_f_svelte',
    'svelte.ts': '_f_svelte',
    razor: '_f_razor',
    mwb: '_f_mwb',
    'mwb.beforefix': '_f_mwb',
    'mwb.bak': '_f_mwb',
    sketch: '_f_sketch',
    dhall: '_f_dhall',
    nix: '_f_nix',
    purs: '_f_purescript',
    purescript: '_f_purescript',
    rkt: '_f_racket',
    scm: '_f_scheme',
    sch: '_f_scheme',
    ss: '_f_scheme',
    rdl: '_f_database',
    j2: '_f_jinja',
    jinja: '_f_jinja',
    jinja2: '_f_jinja',
    vscodeignore: '_f_visualstudiocode',
    editorconfig: '_f_editorconfig',
    sequelizerc: '_f_sequelize',
    npmrc: '_f_npm',
    eslintrc: '_f_eslint',
    'eslintrc.js': '_f_eslint',
    'eslintrc.yml': '_f_eslint',
    'eslintrc.yaml': '_f_eslint',
    'eslintrc.json': '_f_eslint',
    browserlistrc: '_f_browserlist',
    browserslistrc: '_f_browserlist',
    gitkeep: '_f_git',
    abell: '_f_abelljs',
    wasm: '_f_webassembly',
    log: '_f_log',
    txt: '_f_notepad',
    nf: '_f_nextflow',
    def: '_f_singularity',
    f: '_f_fortran',
    for: '_f_fortran',
    f90: '_f_fortran',
    f95: '_f_fortran',
    ftn: '_f_fortran',
    fpp: '_f_fortran',
    polar: '_f_oso',
    adoc: '_f_asciidoc',
    asciidoc: '_f_asciidoc',
    asp: '_f_asp',
    asa: '_f_asp',
    aspx: '_f_asp',
    asax: '_f_asp',
    ascx: '_f_asp',
    vim: '_f_vim',
    proto: '_f_proto',
    gd: '_f_godot',
    tscn: '_f_godot',
    asm: '_f_assembly',
    s: '_f_assembly',
    sentryclirc: '_f_sentry',
    marko: '_f_marko',
    axaml: '_f_avalonia',
    'axaml.cs': '_f_avalonia',
    'model.ts': '_f_model',
    'model.js': '_f_model',
    xi: '_f_xi',
    zig: '_f_zig',
    bf: '_f_brainfuck',
    b: '_f_brainfuck',
    pyx: '_f_cython',
    pxd: '_f_cython',
    'cy.js': '_f_cypress',
    'cy.ts': '_f_cypress',
    'cy.jsx': '_f_cypress',
    mm: '_f_objectivecpp',
    'vr.js': '_f_vr',
    'vr.ts': '_f_vr',
    'vr.jsx': '_f_vr',
    'vr.cjs': '_f_vr',
    sqlbook: '_f_database',
    pro: '_f_prolog',
    'mocha.js': '_f_mocha',
    'mocha.ts': '_f_mocha',
    'mocha.cjs': '_f_mocha',
    groovy: '_f_groovy',
    jenkinsfile: '_f_jenkinsfile',
    yak: '_f_yak',
    function: '_f_function',
    'title-info': '_f_title_info',
    'title-low': '_f_title_low',
    'title-middle': '_f_title_middle',
    'title-high': '_f_title_high',
    'title-fatal': '_f_title_fatal',
};
